version: '3.7'

networks:
  default:
    name: market-main

services:
  app:
    restart: always
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./server/.env
    environment:
      # <<: *mysqlConfig
      APP_DB_HOST: db
      APP_PORT: 3000
      APP_DB_PORT: 3306
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: database-prod
    env_file: ./server/.env
    cap_add:
      - SYS_NICE
  adminer:
    image: adminer
    restart: always
    ports:
      - 7777:8080
    environment: 
      ADMINER_DEFAULT_SERVER: mysql